-- liquibase formatted sql

-- changeset digvijaybhakuni:1745404136752-1
CREATE TABLE "users" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 31) NOT NULL, "username" VARCHAR(255) NOT NULL, "email" VARCHAR(255) NOT NULL, CONSTRAINT "users_pkey" PRIMARY KEY ("id"));

